# Generated by Django 5.0.7 on 2024-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_brand_is_active_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='productline',
            name='ordering',
            field=models.PositiveIntegerField(blank=True, default=0, unique=True),
        ),
    ]
