# Generated by Django 5.0.7 on 2024-07-17 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productline_ordering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productline',
            name='ordering',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alternative_text', models.CharField(max_length=120)),
                ('url', models.ImageField(upload_to=None)),
                ('ordering', models.PositiveIntegerField(default=0, unique=True)),
                ('productline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='product.productline')),
            ],
        ),
    ]
