# Generated by Django 5.0.7 on 2024-07-17 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productline_ordering_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
    ]
